import { prefix } from "./setup_constant.js"
export const external_topic_produce=prefix+"external_topic_produce"
export const external_topic_consume=prefix+"external_topic_consume"
export const internal_topic_produce=prefix+"internal_topic_produce"
export const internal_topic_consume=prefix+"internal_topic_consume"